# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 

#    routing_loader: true

    exception:
        enabled: true
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    
    param_fetcher_listener:
        enabled: true 

    allowed_methods_listener:
        enabled: true

#    body_listener:
#        enabled: true

#    body_converter:
#        enabled: false
        
    format_listener:
        enabled: true 
        rules:
            - { path: ^/, methods: [GET], priorities: [ json], fallback_format: json}
            - { path: ^/, methods: [DELETE, POST, PATCH], priorities: [ xml ], fallback_format: json}


    view:
        view_response_listener:  
          enabled: true
          force: false
        mime_types:
          enabled: true
          formats:
            html: [text/html; charset=UTF-8']
            text: [text/plain; charset=UTF-8']
            xml: [text/xml; charset=UTF-8'; text/plain; ]

    service:
        view_handler: fos_rest.view_handler.default
