sensio_framework_extra:
    router:
        annotations: true
    view:
        annotations: true
    request:
        converters: true
        auto_convert: false
    cache:
        annotations: true
    security:
        annotations: true
