product_list:
    path: /products/{id}
    defaults: {id: 0}
    controller: App\Controller\ProductInStoreController::product_list
    methods: GET

product_delete:
    path: /products/{id}
    controller: App\Controller\ProductInStoreController::product_delete
    methods: DELETE

product_edit:
    path: /products/{id}
    controller: App\Controller\ProductInStoreController::product_edit
    methods: PATCH

product_add:
    path: /products
    controller: App\Controller\ProductInStoreController::product_add
    methods: POST
  

