product_list:
    path: /products
    controller: App\Controller\ProductInStoreController::product_list
    methods: GET

product_delete:
    path: /products/{id}
    controller: App\Controller\ProductInStoreController::product_delete
    methods: DELETE

  

