products_get:
    path: /products/{id}
    defaults: {id: 0}
    controller: App\Controller\ProductInStoreController::productsGet
    methods: GET

product_delete:
    path: /products/{id}
    controller: App\Controller\ProductInStoreController::productDelete
    methods: DELETE

product_edit:
    path: /products/{id}
    controller: App\Controller\ProductInStoreController::productEdit
    methods: PATCH

product_add:
    path: /products
    controller: App\Controller\ProductInStoreController::productAdd
    methods: POST
  

